// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/fileservice/file-service.proto

package fileservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type File struct {
	// Common File Object Structure.
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int32                `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Path                 string               `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	LastModifiedAt       *timestamp.Timestamp `protobuf:"bytes,4,opt,name=lastModifiedAt,proto3" json:"lastModifiedAt,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Creator              string               `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Desc                 string               `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_131fb42dba298879, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *File) GetLastModifiedAt() *timestamp.Timestamp {
	if m != nil {
		return m.LastModifiedAt
	}
	return nil
}

func (m *File) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *File) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *File) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type GoogleDriveFileListRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoogleDriveFileListRequest) Reset()         { *m = GoogleDriveFileListRequest{} }
func (m *GoogleDriveFileListRequest) String() string { return proto.CompactTextString(m) }
func (*GoogleDriveFileListRequest) ProtoMessage()    {}
func (*GoogleDriveFileListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_131fb42dba298879, []int{1}
}

func (m *GoogleDriveFileListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleDriveFileListRequest.Unmarshal(m, b)
}
func (m *GoogleDriveFileListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleDriveFileListRequest.Marshal(b, m, deterministic)
}
func (m *GoogleDriveFileListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleDriveFileListRequest.Merge(m, src)
}
func (m *GoogleDriveFileListRequest) XXX_Size() int {
	return xxx_messageInfo_GoogleDriveFileListRequest.Size(m)
}
func (m *GoogleDriveFileListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleDriveFileListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleDriveFileListRequest proto.InternalMessageInfo

func (m *GoogleDriveFileListRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type GoogleDriveFileListResponse struct {
	File                 []*File              `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
	RequestAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=requestAt,proto3" json:"requestAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GoogleDriveFileListResponse) Reset()         { *m = GoogleDriveFileListResponse{} }
func (m *GoogleDriveFileListResponse) String() string { return proto.CompactTextString(m) }
func (*GoogleDriveFileListResponse) ProtoMessage()    {}
func (*GoogleDriveFileListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_131fb42dba298879, []int{2}
}

func (m *GoogleDriveFileListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleDriveFileListResponse.Unmarshal(m, b)
}
func (m *GoogleDriveFileListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleDriveFileListResponse.Marshal(b, m, deterministic)
}
func (m *GoogleDriveFileListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleDriveFileListResponse.Merge(m, src)
}
func (m *GoogleDriveFileListResponse) XXX_Size() int {
	return xxx_messageInfo_GoogleDriveFileListResponse.Size(m)
}
func (m *GoogleDriveFileListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleDriveFileListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleDriveFileListResponse proto.InternalMessageInfo

func (m *GoogleDriveFileListResponse) GetFile() []*File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *GoogleDriveFileListResponse) GetRequestAt() *timestamp.Timestamp {
	if m != nil {
		return m.RequestAt
	}
	return nil
}

type GoogleStrageFileListRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoogleStrageFileListRequest) Reset()         { *m = GoogleStrageFileListRequest{} }
func (m *GoogleStrageFileListRequest) String() string { return proto.CompactTextString(m) }
func (*GoogleStrageFileListRequest) ProtoMessage()    {}
func (*GoogleStrageFileListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_131fb42dba298879, []int{3}
}

func (m *GoogleStrageFileListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleStrageFileListRequest.Unmarshal(m, b)
}
func (m *GoogleStrageFileListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleStrageFileListRequest.Marshal(b, m, deterministic)
}
func (m *GoogleStrageFileListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleStrageFileListRequest.Merge(m, src)
}
func (m *GoogleStrageFileListRequest) XXX_Size() int {
	return xxx_messageInfo_GoogleStrageFileListRequest.Size(m)
}
func (m *GoogleStrageFileListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleStrageFileListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleStrageFileListRequest proto.InternalMessageInfo

func (m *GoogleStrageFileListRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type GoogleStrageFileListResponse struct {
	File                 []*File              `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
	RequestAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=requestAt,proto3" json:"requestAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GoogleStrageFileListResponse) Reset()         { *m = GoogleStrageFileListResponse{} }
func (m *GoogleStrageFileListResponse) String() string { return proto.CompactTextString(m) }
func (*GoogleStrageFileListResponse) ProtoMessage()    {}
func (*GoogleStrageFileListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_131fb42dba298879, []int{4}
}

func (m *GoogleStrageFileListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleStrageFileListResponse.Unmarshal(m, b)
}
func (m *GoogleStrageFileListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleStrageFileListResponse.Marshal(b, m, deterministic)
}
func (m *GoogleStrageFileListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleStrageFileListResponse.Merge(m, src)
}
func (m *GoogleStrageFileListResponse) XXX_Size() int {
	return xxx_messageInfo_GoogleStrageFileListResponse.Size(m)
}
func (m *GoogleStrageFileListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleStrageFileListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleStrageFileListResponse proto.InternalMessageInfo

func (m *GoogleStrageFileListResponse) GetFile() []*File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *GoogleStrageFileListResponse) GetRequestAt() *timestamp.Timestamp {
	if m != nil {
		return m.RequestAt
	}
	return nil
}

func init() {
	proto.RegisterType((*File)(nil), "fileservice.File")
	proto.RegisterType((*GoogleDriveFileListRequest)(nil), "fileservice.GoogleDriveFileListRequest")
	proto.RegisterType((*GoogleDriveFileListResponse)(nil), "fileservice.GoogleDriveFileListResponse")
	proto.RegisterType((*GoogleStrageFileListRequest)(nil), "fileservice.GoogleStrageFileListRequest")
	proto.RegisterType((*GoogleStrageFileListResponse)(nil), "fileservice.GoogleStrageFileListResponse")
}

func init() { proto.RegisterFile("api/fileservice/file-service.proto", fileDescriptor_131fb42dba298879) }

var fileDescriptor_131fb42dba298879 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x51, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x96, 0xdb, 0xb4, 0x55, 0x1d, 0x09, 0x54, 0x23, 0x51, 0x13, 0x2a, 0x11, 0x45, 0x42, 0x84,
	0x03, 0x09, 0x2d, 0x17, 0xae, 0x45, 0x88, 0x5e, 0xe0, 0x92, 0xf2, 0x02, 0x6e, 0x33, 0x0d, 0x96,
	0xd2, 0x38, 0xc4, 0x6e, 0x0f, 0x1c, 0x40, 0x42, 0x5c, 0x38, 0xf3, 0x02, 0xbc, 0xd3, 0xbe, 0xc2,
	0x9e, 0xf7, 0x19, 0x56, 0xb6, 0x9b, 0xfe, 0xac, 0xb2, 0x6a, 0x4f, 0x7b, 0x9b, 0xb1, 0xbf, 0x6f,
	0xbe, 0xef, 0x9b, 0xc1, 0x01, 0x2b, 0x79, 0xbc, 0xe2, 0x39, 0x48, 0xa8, 0xb6, 0x7c, 0x09, 0xa6,
	0x7e, 0xb3, 0x6b, 0xa2, 0xb2, 0x12, 0x4a, 0x10, 0xf7, 0xe8, 0xdf, 0x1b, 0x65, 0x42, 0x64, 0x39,
	0xc4, 0x9a, 0xc7, 0x8a, 0x42, 0x28, 0xa6, 0xb8, 0x28, 0xa4, 0x85, 0x7a, 0x2f, 0x76, 0xbf, 0xa6,
	0x5b, 0x6c, 0x56, 0xb1, 0xe2, 0x6b, 0x90, 0x8a, 0xad, 0x4b, 0x0b, 0x08, 0x6e, 0x10, 0x76, 0x3e,
	0xf1, 0x1c, 0x08, 0xc1, 0x4e, 0xc1, 0xd6, 0x40, 0x91, 0x8f, 0xc2, 0x7e, 0x62, 0x6a, 0xfd, 0x26,
	0xf9, 0x0f, 0xa0, 0x2d, 0x1f, 0x85, 0x9d, 0xc4, 0xd4, 0xfa, 0xad, 0x64, 0xea, 0x1b, 0x6d, 0x5b,
	0x9c, 0xae, 0xc9, 0x07, 0xfc, 0x28, 0x67, 0x52, 0x7d, 0x11, 0x29, 0x5f, 0x71, 0x48, 0xa7, 0x8a,
	0x3a, 0x3e, 0x0a, 0xdd, 0x89, 0x17, 0x59, 0xf9, 0xa8, 0x96, 0x8f, 0xbe, 0xd6, 0xf2, 0xc9, 0x1d,
	0x06, 0x79, 0x8f, 0xfb, 0xcb, 0x0a, 0x98, 0x32, 0xf4, 0xce, 0x59, 0xfa, 0x01, 0x4c, 0x28, 0xee,
	0x99, 0x46, 0x54, 0xb4, 0x6b, 0x4c, 0xd5, 0xad, 0xf6, 0x9a, 0x82, 0x5c, 0xd2, 0x9e, 0xf5, 0xaa,
	0xeb, 0xe0, 0x2d, 0xf6, 0x66, 0x66, 0xea, 0xc7, 0x8a, 0x6f, 0x41, 0x47, 0xff, 0xcc, 0xa5, 0x4a,
	0xe0, 0xfb, 0x06, 0xa4, 0xda, 0xa7, 0x43, 0x87, 0x74, 0xc1, 0x4f, 0xfc, 0xbc, 0x91, 0x21, 0x4b,
	0x51, 0x48, 0x20, 0x2f, 0xb1, 0xa3, 0xef, 0x41, 0x91, 0xdf, 0x0e, 0xdd, 0xc9, 0x20, 0x3a, 0x3a,
	0x4e, 0xa4, 0xc1, 0x89, 0xf9, 0xd6, 0xf9, 0x2a, 0x2b, 0x32, 0x55, 0x66, 0xa1, 0x67, 0xf2, 0xed,
	0xc1, 0xc1, 0xb8, 0xd6, 0x9f, 0xab, 0x8a, 0x65, 0x17, 0x59, 0xfe, 0x85, 0x47, 0xcd, 0x94, 0x07,
	0xf2, 0x3c, 0xf9, 0xdf, 0xc2, 0xae, 0x1e, 0x34, 0xb7, 0x43, 0xc9, 0x1f, 0x84, 0x9f, 0xce, 0x40,
	0x35, 0xec, 0x91, 0xbc, 0x3a, 0x51, 0xbf, 0xff, 0x36, 0x5e, 0x78, 0x1e, 0x68, 0xe3, 0x05, 0xc3,
	0xdf, 0x57, 0xd7, 0xff, 0x5a, 0x03, 0xf2, 0x38, 0xde, 0x8e, 0xe3, 0x2c, 0xd5, 0x98, 0x38, 0xd7,
	0x5a, 0x7f, 0x11, 0x1e, 0xee, 0x6d, 0x9c, 0xee, 0x86, 0x34, 0x8d, 0x6f, 0xdc, 0xb8, 0xf7, 0xfa,
	0x02, 0xe4, 0xce, 0xc9, 0x33, 0xe3, 0xe4, 0x09, 0x19, 0x18, 0x27, 0x52, 0x09, 0x8d, 0x32, 0x5e,
	0x16, 0x5d, 0xb3, 0xc1, 0x77, 0xb7, 0x01, 0x00, 0x00, 0xff, 0xff, 0x15, 0xf2, 0x19, 0x79, 0xf2,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileServiceClient interface {
	GetGoogleDriveFileList(ctx context.Context, in *GoogleDriveFileListRequest, opts ...grpc.CallOption) (*GoogleDriveFileListResponse, error)
	GetGoogleStrageFileList(ctx context.Context, in *GoogleStrageFileListRequest, opts ...grpc.CallOption) (*GoogleStrageFileListResponse, error)
}

type fileServiceClient struct {
	cc *grpc.ClientConn
}

func NewFileServiceClient(cc *grpc.ClientConn) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) GetGoogleDriveFileList(ctx context.Context, in *GoogleDriveFileListRequest, opts ...grpc.CallOption) (*GoogleDriveFileListResponse, error) {
	out := new(GoogleDriveFileListResponse)
	err := c.cc.Invoke(ctx, "/fileservice.FileService/GetGoogleDriveFileList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetGoogleStrageFileList(ctx context.Context, in *GoogleStrageFileListRequest, opts ...grpc.CallOption) (*GoogleStrageFileListResponse, error) {
	out := new(GoogleStrageFileListResponse)
	err := c.cc.Invoke(ctx, "/fileservice.FileService/GetGoogleStrageFileList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
type FileServiceServer interface {
	GetGoogleDriveFileList(context.Context, *GoogleDriveFileListRequest) (*GoogleDriveFileListResponse, error)
	GetGoogleStrageFileList(context.Context, *GoogleStrageFileListRequest) (*GoogleStrageFileListResponse, error)
}

// UnimplementedFileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFileServiceServer struct {
}

func (*UnimplementedFileServiceServer) GetGoogleDriveFileList(ctx context.Context, req *GoogleDriveFileListRequest) (*GoogleDriveFileListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoogleDriveFileList not implemented")
}
func (*UnimplementedFileServiceServer) GetGoogleStrageFileList(ctx context.Context, req *GoogleStrageFileListRequest) (*GoogleStrageFileListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoogleStrageFileList not implemented")
}

func RegisterFileServiceServer(s *grpc.Server, srv FileServiceServer) {
	s.RegisterService(&_FileService_serviceDesc, srv)
}

func _FileService_GetGoogleDriveFileList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleDriveFileListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetGoogleDriveFileList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fileservice.FileService/GetGoogleDriveFileList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetGoogleDriveFileList(ctx, req.(*GoogleDriveFileListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetGoogleStrageFileList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleStrageFileListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetGoogleStrageFileList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fileservice.FileService/GetGoogleStrageFileList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetGoogleStrageFileList(ctx, req.(*GoogleStrageFileListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fileservice.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGoogleDriveFileList",
			Handler:    _FileService_GetGoogleDriveFileList_Handler,
		},
		{
			MethodName: "GetGoogleStrageFileList",
			Handler:    _FileService_GetGoogleStrageFileList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/fileservice/file-service.proto",
}
