// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/fileservice/file-service.proto

package fileservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type File struct {
	// Common File Object Structure.
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int32                `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Data                 []byte               `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Path                 string               `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	LastModifiedAt       *timestamp.Timestamp `protobuf:"bytes,5,opt,name=lastModifiedAt,proto3" json:"lastModifiedAt,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Creator              string               `protobuf:"bytes,7,opt,name=creator,proto3" json:"creator,omitempty"`
	Desc                 string               `protobuf:"bytes,8,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_131fb42dba298879, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *File) GetLastModifiedAt() *timestamp.Timestamp {
	if m != nil {
		return m.LastModifiedAt
	}
	return nil
}

func (m *File) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *File) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *File) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type GoogleDriveFileListRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoogleDriveFileListRequest) Reset()         { *m = GoogleDriveFileListRequest{} }
func (m *GoogleDriveFileListRequest) String() string { return proto.CompactTextString(m) }
func (*GoogleDriveFileListRequest) ProtoMessage()    {}
func (*GoogleDriveFileListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_131fb42dba298879, []int{1}
}

func (m *GoogleDriveFileListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleDriveFileListRequest.Unmarshal(m, b)
}
func (m *GoogleDriveFileListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleDriveFileListRequest.Marshal(b, m, deterministic)
}
func (m *GoogleDriveFileListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleDriveFileListRequest.Merge(m, src)
}
func (m *GoogleDriveFileListRequest) XXX_Size() int {
	return xxx_messageInfo_GoogleDriveFileListRequest.Size(m)
}
func (m *GoogleDriveFileListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleDriveFileListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleDriveFileListRequest proto.InternalMessageInfo

func (m *GoogleDriveFileListRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type GoogleDriveFileListResponse struct {
	File                 []*File              `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
	RequestAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=requestAt,proto3" json:"requestAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GoogleDriveFileListResponse) Reset()         { *m = GoogleDriveFileListResponse{} }
func (m *GoogleDriveFileListResponse) String() string { return proto.CompactTextString(m) }
func (*GoogleDriveFileListResponse) ProtoMessage()    {}
func (*GoogleDriveFileListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_131fb42dba298879, []int{2}
}

func (m *GoogleDriveFileListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleDriveFileListResponse.Unmarshal(m, b)
}
func (m *GoogleDriveFileListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleDriveFileListResponse.Marshal(b, m, deterministic)
}
func (m *GoogleDriveFileListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleDriveFileListResponse.Merge(m, src)
}
func (m *GoogleDriveFileListResponse) XXX_Size() int {
	return xxx_messageInfo_GoogleDriveFileListResponse.Size(m)
}
func (m *GoogleDriveFileListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleDriveFileListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleDriveFileListResponse proto.InternalMessageInfo

func (m *GoogleDriveFileListResponse) GetFile() []*File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *GoogleDriveFileListResponse) GetRequestAt() *timestamp.Timestamp {
	if m != nil {
		return m.RequestAt
	}
	return nil
}

type GoogleStorageFileListRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoogleStorageFileListRequest) Reset()         { *m = GoogleStorageFileListRequest{} }
func (m *GoogleStorageFileListRequest) String() string { return proto.CompactTextString(m) }
func (*GoogleStorageFileListRequest) ProtoMessage()    {}
func (*GoogleStorageFileListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_131fb42dba298879, []int{3}
}

func (m *GoogleStorageFileListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleStorageFileListRequest.Unmarshal(m, b)
}
func (m *GoogleStorageFileListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleStorageFileListRequest.Marshal(b, m, deterministic)
}
func (m *GoogleStorageFileListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleStorageFileListRequest.Merge(m, src)
}
func (m *GoogleStorageFileListRequest) XXX_Size() int {
	return xxx_messageInfo_GoogleStorageFileListRequest.Size(m)
}
func (m *GoogleStorageFileListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleStorageFileListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleStorageFileListRequest proto.InternalMessageInfo

func (m *GoogleStorageFileListRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type GoogleStorageFileListResponse struct {
	File                 []*File              `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
	RequestAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=requestAt,proto3" json:"requestAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GoogleStorageFileListResponse) Reset()         { *m = GoogleStorageFileListResponse{} }
func (m *GoogleStorageFileListResponse) String() string { return proto.CompactTextString(m) }
func (*GoogleStorageFileListResponse) ProtoMessage()    {}
func (*GoogleStorageFileListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_131fb42dba298879, []int{4}
}

func (m *GoogleStorageFileListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleStorageFileListResponse.Unmarshal(m, b)
}
func (m *GoogleStorageFileListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleStorageFileListResponse.Marshal(b, m, deterministic)
}
func (m *GoogleStorageFileListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleStorageFileListResponse.Merge(m, src)
}
func (m *GoogleStorageFileListResponse) XXX_Size() int {
	return xxx_messageInfo_GoogleStorageFileListResponse.Size(m)
}
func (m *GoogleStorageFileListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleStorageFileListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleStorageFileListResponse proto.InternalMessageInfo

func (m *GoogleStorageFileListResponse) GetFile() []*File {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *GoogleStorageFileListResponse) GetRequestAt() *timestamp.Timestamp {
	if m != nil {
		return m.RequestAt
	}
	return nil
}

type GoogleStorageFileRequest struct {
	Base64Id             string   `protobuf:"bytes,1,opt,name=base64Id,proto3" json:"base64Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoogleStorageFileRequest) Reset()         { *m = GoogleStorageFileRequest{} }
func (m *GoogleStorageFileRequest) String() string { return proto.CompactTextString(m) }
func (*GoogleStorageFileRequest) ProtoMessage()    {}
func (*GoogleStorageFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_131fb42dba298879, []int{5}
}

func (m *GoogleStorageFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleStorageFileRequest.Unmarshal(m, b)
}
func (m *GoogleStorageFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleStorageFileRequest.Marshal(b, m, deterministic)
}
func (m *GoogleStorageFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleStorageFileRequest.Merge(m, src)
}
func (m *GoogleStorageFileRequest) XXX_Size() int {
	return xxx_messageInfo_GoogleStorageFileRequest.Size(m)
}
func (m *GoogleStorageFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleStorageFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleStorageFileRequest proto.InternalMessageInfo

func (m *GoogleStorageFileRequest) GetBase64Id() string {
	if m != nil {
		return m.Base64Id
	}
	return ""
}

type GoogleStorageFileResponse struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoogleStorageFileResponse) Reset()         { *m = GoogleStorageFileResponse{} }
func (m *GoogleStorageFileResponse) String() string { return proto.CompactTextString(m) }
func (*GoogleStorageFileResponse) ProtoMessage()    {}
func (*GoogleStorageFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_131fb42dba298879, []int{6}
}

func (m *GoogleStorageFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleStorageFileResponse.Unmarshal(m, b)
}
func (m *GoogleStorageFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleStorageFileResponse.Marshal(b, m, deterministic)
}
func (m *GoogleStorageFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleStorageFileResponse.Merge(m, src)
}
func (m *GoogleStorageFileResponse) XXX_Size() int {
	return xxx_messageInfo_GoogleStorageFileResponse.Size(m)
}
func (m *GoogleStorageFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleStorageFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleStorageFileResponse proto.InternalMessageInfo

func (m *GoogleStorageFileResponse) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func init() {
	proto.RegisterType((*File)(nil), "fileservice.File")
	proto.RegisterType((*GoogleDriveFileListRequest)(nil), "fileservice.GoogleDriveFileListRequest")
	proto.RegisterType((*GoogleDriveFileListResponse)(nil), "fileservice.GoogleDriveFileListResponse")
	proto.RegisterType((*GoogleStorageFileListRequest)(nil), "fileservice.GoogleStorageFileListRequest")
	proto.RegisterType((*GoogleStorageFileListResponse)(nil), "fileservice.GoogleStorageFileListResponse")
	proto.RegisterType((*GoogleStorageFileRequest)(nil), "fileservice.GoogleStorageFileRequest")
	proto.RegisterType((*GoogleStorageFileResponse)(nil), "fileservice.GoogleStorageFileResponse")
}

func init() { proto.RegisterFile("api/fileservice/file-service.proto", fileDescriptor_131fb42dba298879) }

var fileDescriptor_131fb42dba298879 = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0xc7, 0xe5, 0xdd, 0xed, 0x97, 0x17, 0x81, 0xd6, 0x20, 0x70, 0x43, 0xab, 0x46, 0x91, 0x16,
	0x02, 0x12, 0x09, 0x2c, 0xa8, 0xe2, 0xda, 0x0a, 0x51, 0x21, 0xc1, 0x25, 0xe5, 0x05, 0xbc, 0x9b,
	0xd9, 0xc5, 0x52, 0x36, 0x0e, 0xb1, 0xbb, 0x07, 0x10, 0x08, 0x55, 0x1c, 0xb9, 0xf1, 0x26, 0xbc,
	0x0a, 0xaf, 0xc0, 0x83, 0x20, 0x8f, 0x93, 0xf4, 0x2b, 0xed, 0xf6, 0xd4, 0xdb, 0x8c, 0xe7, 0xff,
	0x1f, 0xff, 0xc6, 0x63, 0x1a, 0x88, 0x42, 0xc6, 0x53, 0x99, 0x81, 0x86, 0x72, 0x21, 0x27, 0x80,
	0xf1, 0xb3, 0x2a, 0x89, 0x8a, 0x52, 0x19, 0xc5, 0xfa, 0xa7, 0xea, 0xde, 0xd6, 0x4c, 0xa9, 0x59,
	0x06, 0xb1, 0xf5, 0x89, 0x3c, 0x57, 0x46, 0x18, 0xa9, 0x72, 0xed, 0xa4, 0xde, 0x4e, 0x55, 0xc5,
	0x6c, 0x7c, 0x34, 0x8d, 0x8d, 0x9c, 0x83, 0x36, 0x62, 0x5e, 0x38, 0x41, 0x70, 0xdc, 0xa1, 0xbd,
	0xb7, 0x32, 0x03, 0xc6, 0x68, 0x2f, 0x17, 0x73, 0xe0, 0xc4, 0x27, 0xe1, 0x46, 0x82, 0xb1, 0x3d,
	0xd3, 0xf2, 0x0b, 0xf0, 0x8e, 0x4f, 0xc2, 0x95, 0x04, 0x63, 0x7b, 0x96, 0x0a, 0x23, 0x78, 0xd7,
	0x27, 0xe1, 0xad, 0x04, 0x63, 0x7b, 0x56, 0x08, 0xf3, 0x89, 0xf7, 0x9c, 0xd7, 0xc6, 0x6c, 0x9f,
	0xde, 0xce, 0x84, 0x36, 0x1f, 0x54, 0x2a, 0xa7, 0x12, 0xd2, 0x3d, 0xc3, 0x57, 0x7c, 0x12, 0xf6,
	0x47, 0x5e, 0xe4, 0x90, 0xa2, 0x1a, 0x29, 0xfa, 0x58, 0x23, 0x25, 0xe7, 0x1c, 0xec, 0x35, 0xdd,
	0x98, 0x94, 0x20, 0x0c, 0xda, 0x57, 0x97, 0xda, 0x4f, 0xc4, 0x8c, 0xd3, 0x35, 0x4c, 0x54, 0xc9,
	0xd7, 0x10, 0xaa, 0x4e, 0x91, 0x1f, 0xf4, 0x84, 0xaf, 0x3b, 0x56, 0x1b, 0x07, 0xcf, 0xa9, 0x77,
	0x80, 0x5d, 0xdf, 0x94, 0x72, 0x01, 0xf6, 0x39, 0xde, 0x4b, 0x6d, 0x12, 0xf8, 0x7c, 0x04, 0xda,
	0x34, 0xd3, 0x91, 0x93, 0xe9, 0x82, 0xef, 0xf4, 0x61, 0xab, 0x43, 0x17, 0x2a, 0xd7, 0xc0, 0x86,
	0xb4, 0x67, 0x77, 0xc4, 0x89, 0xdf, 0x0d, 0xfb, 0xa3, 0x41, 0x74, 0x6a, 0x61, 0x91, 0x15, 0x27,
	0x58, 0xb6, 0xf3, 0x95, 0xee, 0x92, 0x3d, 0x83, 0x8f, 0xbc, 0x64, 0xbe, 0x46, 0x1c, 0x8c, 0xe8,
	0x96, 0xbb, 0xff, 0xd0, 0xa8, 0x52, 0xcc, 0xae, 0xc5, 0xfc, 0x83, 0xd0, 0xed, 0x4b, 0x4c, 0x37,
	0x85, 0xbd, 0x4b, 0xf9, 0x05, 0x82, 0x1a, 0xd9, 0xa3, 0xeb, 0x63, 0xa1, 0x61, 0xf7, 0xd5, 0xbb,
	0xb4, 0xc2, 0x6e, 0xf2, 0x60, 0x9f, 0x6e, 0xb6, 0xf8, 0x2e, 0x50, 0x93, 0x2b, 0xa8, 0x47, 0x7f,
	0xba, 0xb4, 0x6f, 0xd3, 0x43, 0x57, 0x62, 0x3f, 0x09, 0xbd, 0x7f, 0x00, 0xa6, 0x65, 0x8d, 0xec,
	0xf1, 0x99, 0x1e, 0x97, 0x7f, 0x0d, 0x2f, 0x5c, 0x2e, 0x74, 0x90, 0xc1, 0x83, 0xe3, 0xbf, 0xff,
	0x7e, 0x77, 0x06, 0xec, 0x4e, 0xbc, 0x78, 0x11, 0xcf, 0x52, 0xab, 0x89, 0x33, 0x7b, 0xd7, 0x2f,
	0x42, 0x79, 0x83, 0x71, 0x6e, 0x31, 0xec, 0x49, 0x4b, 0xff, 0xf6, 0x8d, 0x7b, 0x4f, 0xaf, 0x23,
	0xad, 0x60, 0x36, 0x11, 0xe6, 0x2e, 0x1b, 0x20, 0x8c, 0x76, 0xaa, 0x06, 0xe7, 0x5e, 0x1b, 0x0e,
	0x1b, 0x5e, 0xdd, 0xbf, 0xc6, 0x78, 0xb4, 0x4c, 0x56, 0x21, 0x0c, 0x11, 0x61, 0x87, 0x6d, 0x9f,
	0x41, 0x40, 0x6f, 0xfc, 0xb5, 0xde, 0xfb, 0xb7, 0xf1, 0x2a, 0xfe, 0xa7, 0x97, 0xff, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xc4, 0x1c, 0xa2, 0xa1, 0x17, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileServiceClient interface {
	GetGoogleDriveFileList(ctx context.Context, in *GoogleDriveFileListRequest, opts ...grpc.CallOption) (*GoogleDriveFileListResponse, error)
	GetGoogleStorageFileList(ctx context.Context, in *GoogleStorageFileListRequest, opts ...grpc.CallOption) (*GoogleStorageFileListResponse, error)
	GetGoogleStorageFile(ctx context.Context, in *GoogleStorageFileRequest, opts ...grpc.CallOption) (*GoogleStorageFileResponse, error)
}

type fileServiceClient struct {
	cc *grpc.ClientConn
}

func NewFileServiceClient(cc *grpc.ClientConn) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) GetGoogleDriveFileList(ctx context.Context, in *GoogleDriveFileListRequest, opts ...grpc.CallOption) (*GoogleDriveFileListResponse, error) {
	out := new(GoogleDriveFileListResponse)
	err := c.cc.Invoke(ctx, "/fileservice.FileService/GetGoogleDriveFileList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetGoogleStorageFileList(ctx context.Context, in *GoogleStorageFileListRequest, opts ...grpc.CallOption) (*GoogleStorageFileListResponse, error) {
	out := new(GoogleStorageFileListResponse)
	err := c.cc.Invoke(ctx, "/fileservice.FileService/GetGoogleStorageFileList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetGoogleStorageFile(ctx context.Context, in *GoogleStorageFileRequest, opts ...grpc.CallOption) (*GoogleStorageFileResponse, error) {
	out := new(GoogleStorageFileResponse)
	err := c.cc.Invoke(ctx, "/fileservice.FileService/GetGoogleStorageFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
type FileServiceServer interface {
	GetGoogleDriveFileList(context.Context, *GoogleDriveFileListRequest) (*GoogleDriveFileListResponse, error)
	GetGoogleStorageFileList(context.Context, *GoogleStorageFileListRequest) (*GoogleStorageFileListResponse, error)
	GetGoogleStorageFile(context.Context, *GoogleStorageFileRequest) (*GoogleStorageFileResponse, error)
}

// UnimplementedFileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFileServiceServer struct {
}

func (*UnimplementedFileServiceServer) GetGoogleDriveFileList(ctx context.Context, req *GoogleDriveFileListRequest) (*GoogleDriveFileListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoogleDriveFileList not implemented")
}
func (*UnimplementedFileServiceServer) GetGoogleStorageFileList(ctx context.Context, req *GoogleStorageFileListRequest) (*GoogleStorageFileListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoogleStorageFileList not implemented")
}
func (*UnimplementedFileServiceServer) GetGoogleStorageFile(ctx context.Context, req *GoogleStorageFileRequest) (*GoogleStorageFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoogleStorageFile not implemented")
}

func RegisterFileServiceServer(s *grpc.Server, srv FileServiceServer) {
	s.RegisterService(&_FileService_serviceDesc, srv)
}

func _FileService_GetGoogleDriveFileList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleDriveFileListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetGoogleDriveFileList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fileservice.FileService/GetGoogleDriveFileList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetGoogleDriveFileList(ctx, req.(*GoogleDriveFileListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetGoogleStorageFileList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleStorageFileListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetGoogleStorageFileList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fileservice.FileService/GetGoogleStorageFileList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetGoogleStorageFileList(ctx, req.(*GoogleStorageFileListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetGoogleStorageFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleStorageFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetGoogleStorageFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fileservice.FileService/GetGoogleStorageFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetGoogleStorageFile(ctx, req.(*GoogleStorageFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fileservice.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGoogleDriveFileList",
			Handler:    _FileService_GetGoogleDriveFileList_Handler,
		},
		{
			MethodName: "GetGoogleStorageFileList",
			Handler:    _FileService_GetGoogleStorageFileList_Handler,
		},
		{
			MethodName: "GetGoogleStorageFile",
			Handler:    _FileService_GetGoogleStorageFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/fileservice/file-service.proto",
}
